-- Generated from @money/database. Do not edit manually.
SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS klines (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    open_time BIGINT NOT NULL,
    bid_open DECIMAL(20, 8) NOT NULL,
    bid_high DECIMAL(20, 8) NOT NULL,
    bid_low DECIMAL(20, 8) NOT NULL,
    bid_close DECIMAL(20, 8) NOT NULL,
    ask_open DECIMAL(20, 8) NOT NULL,
    ask_high DECIMAL(20, 8) NOT NULL,
    ask_low DECIMAL(20, 8) NOT NULL,
    ask_close DECIMAL(20, 8) NOT NULL,
    volume DECIMAL(20, 8) DEFAULT 0,
    symbol VARCHAR(20) DEFAULT 'USDJPY',
    interval_type VARCHAR(10) DEFAULT '1m',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_kline (symbol, interval_type, open_time),
    INDEX idx_open_time (open_time),
    INDEX idx_symbol_time (symbol, open_time)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trades (
    id INT AUTO_INCREMENT PRIMARY KEY,
    direction ENUM('long', 'short') NOT NULL,
    entry_time BIGINT NOT NULL,
    entry_price DECIMAL(20, 8) NOT NULL,
    entry_index INT,
    entry_rsi DECIMAL(6, 2),
    entry_macd DECIMAL(20, 8),
    entry_macd_signal DECIMAL(20, 8),
    entry_macd_histogram DECIMAL(20, 8),
    lot_size DECIMAL(10, 2) NOT NULL DEFAULT 1.00,
    hold_minutes INT,
    stop_loss DECIMAL(20, 8),
    take_profit DECIMAL(20, 8),
    exit_time BIGINT NOT NULL,
    exit_price DECIMAL(20, 8) NOT NULL,
    exit_rsi DECIMAL(6, 2),
    exit_macd DECIMAL(20, 8),
    exit_macd_signal DECIMAL(20, 8),
    exit_macd_histogram DECIMAL(20, 8),
    exit_reason ENUM(
      'stop_loss',
      'take_profit',
      'hold_time_reached',
      'trailing_stop',
      'rsi_revert',
      'no_overnight',
      'no_weekend',
      'backtest_end',
      'manual'
    ),
    gross_pnl DECIMAL(10, 2),
    commission_fee DECIMAL(10, 4),
    pnl DECIMAL(10, 2),
    pips DECIMAL(10, 2),
    percent DECIMAL(10, 4),
    actual_hold_minutes INT,
    strategy_name VARCHAR(255),
    symbol VARCHAR(20) DEFAULT 'USDJPY',
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_direction (direction),
    INDEX idx_entry_time (entry_time),
    INDEX idx_exit_time (exit_time),
    INDEX idx_strategy_name (strategy_name),
    INDEX idx_symbol (symbol),
    INDEX idx_pnl (pnl)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS strategies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    parameters JSON NOT NULL,
    type VARCHAR(50),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_name (name),
    INDEX idx_type (type),
    INDEX idx_is_active (is_active)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS backtest_results (
    id INT AUTO_INCREMENT PRIMARY KEY,
    result_group VARCHAR(255) NOT NULL COMMENT 'logical result group',
    run_id VARCHAR(64) NOT NULL COMMENT 'single training or validation run id',
    config_name VARCHAR(255) NULL COMMENT 'config name',
    mode VARCHAR(20) NULL COMMENT 'training / validation',
    symbol VARCHAR(20) NULL COMMENT 'market symbol',
    interval_type VARCHAR(20) NULL COMMENT 'kline interval',
    period_start_ms BIGINT NULL COMMENT 'period start timestamp in ms',
    period_end_ms BIGINT NULL COMMENT 'period end timestamp in ms',
    strategy_name VARCHAR(255) NOT NULL,
    strategy_type VARCHAR(50),
    parameters JSON,
    total_trades INT DEFAULT 0,
    winning_trades INT DEFAULT 0,
    losing_trades INT DEFAULT 0,
    win_rate DECIMAL(5, 4) DEFAULT 0,
    gross_pnl DECIMAL(15, 2) DEFAULT 0,
    total_commission DECIMAL(15, 4) DEFAULT 0,
    total_pnl DECIMAL(15, 2) DEFAULT 0,
    return_pct DECIMAL(12, 4) DEFAULT 0,
    avg_pnl DECIMAL(15, 2) DEFAULT 0,
    max_drawdown DECIMAL(15, 2) DEFAULT 0,
    max_drawdown_pct DECIMAL(10, 4) DEFAULT 0,
    gross_profit DECIMAL(15, 2) DEFAULT 0,
    gross_loss DECIMAL(15, 2) DEFAULT 0,
    sharpe_ratio DECIMAL(10, 4) DEFAULT 0,
    profit_factor DECIMAL(10, 4) DEFAULT 0,
    avg_win DECIMAL(15, 2) DEFAULT 0,
    avg_loss DECIMAL(15, 2) DEFAULT 0,
    max_win DECIMAL(15, 2) DEFAULT 0,
    max_loss DECIMAL(15, 2) DEFAULT 0,
    score DECIMAL(15, 4) DEFAULT 0,
    executor_version VARCHAR(20) NULL,
    executor_options JSON NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_result_group (result_group),
    INDEX idx_result_group_run_id (result_group, run_id),
    INDEX idx_symbol_mode (symbol, mode),
    INDEX idx_strategy_name (strategy_name),
    INDEX idx_total_pnl (total_pnl),
    INDEX idx_win_rate (win_rate),
    INDEX idx_sharpe_ratio (sharpe_ratio),
    INDEX idx_score (score),
    UNIQUE KEY uniq_result_group_run_strategy (result_group, run_id, strategy_name)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task_id VARCHAR(100) NOT NULL UNIQUE,
    config_name VARCHAR(255) NOT NULL,
    description TEXT,
    status ENUM('pending', 'running', 'completed', 'failed') DEFAULT 'pending',
    pid INT,
    started_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_status (status),
    INDEX idx_task_id (task_id),
    INDEX idx_config_name (config_name),
    INDEX idx_pid (pid)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS train_configs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    config_key VARCHAR(255) NOT NULL COMMENT 'stable key relative to train/',
    config_type VARCHAR(50) NOT NULL COMMENT 'training / validation / top-strategies / router / generated / config',
    config_name VARCHAR(255) NULL COMMENT 'json name field',
    symbol VARCHAR(20) NULL COMMENT 'market symbol',
    interval_type VARCHAR(20) NULL COMMENT 'kline interval',
    result_group VARCHAR(255) NULL COMMENT 'database.tableName',
    source_table VARCHAR(255) NULL COMMENT 'top-strategies.sourceTable',
    train_config_ref VARCHAR(255) NULL COMMENT 'top-strategies.trainConfig',
    training_year VARCHAR(10) NULL COMMENT 'training year label',
    is_generated TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'generated config flag',
    content_hash VARCHAR(64) NOT NULL COMMENT 'content hash',
    content JSON NOT NULL COMMENT 'full config json',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_config_key (config_key),
    INDEX idx_config_type (config_type),
    INDEX idx_config_name (config_name),
    INDEX idx_symbol_type (symbol, config_type),
    INDEX idx_result_group (result_group),
    INDEX idx_training_year (training_year)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS train_run_requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    request_id VARCHAR(100) NOT NULL,
    config_id INT NOT NULL,
    config_key VARCHAR(255) NOT NULL,
    config_name VARCHAR(255) NULL,
    config_type VARCHAR(50) NOT NULL,
    action VARCHAR(20) NOT NULL COMMENT 'train / validate',
    status VARCHAR(20) NOT NULL COMMENT 'queued / exporting / running / completed / failed / cancelled',
    requested_by VARCHAR(100) NULL,
    trigger_source VARCHAR(50) NOT NULL DEFAULT 'ui',
    command_text TEXT NULL,
    export_path VARCHAR(500) NULL,
    worker_pid INT NULL,
    execution_pid INT NULL,
    cancel_requested TINYINT(1) NOT NULL DEFAULT 0,
    attempt_count INT NOT NULL DEFAULT 0,
    log_excerpt MEDIUMTEXT NULL,
    error_message TEXT NULL,
    started_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_request_id (request_id),
    INDEX idx_status_created (status, created_at),
    INDEX idx_config_id (config_id),
    INDEX idx_config_key (config_key),
    INDEX idx_action_status (action, status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
