const TABLES = Object.freeze({
  BACKTEST_RESULTS: 'backtest_results',
  KLINES: 'klines',
  STRATEGIES: 'strategies',
  TASKS: 'tasks',
  TRADES: 'trades',
  TRAIN_CONFIGS: 'train_configs',
  TRAIN_GOAL_TRACKING: 'train_goal_tracking',
  TRAINING_CONFIG_DETAILS: 'training_config_details',
  VALIDATION_CONFIG_DETAILS: 'validation_config_details',
  SNAPSHOT_CONFIG_DETAILS: 'snapshot_config_details',
  ROLLING_POOL_DETAILS: 'rolling_pool_details',
  ROLLING_RULE_DETAILS: 'rolling_rule_details',
  ROUTER_CONFIG_DETAILS: 'router_config_details',
  POLICY_CONFIG_DETAILS: 'policy_config_details',
  GENERIC_CONFIG_DETAILS: 'generic_config_details',
  TRAIN_RUN_REQUESTS: 'train_run_requests',
  TRAIN_ARTIFACTS: 'train_artifacts'
});

module.exports = {
  BACKTEST_RESULTS_TABLE: TABLES.BACKTEST_RESULTS,
  TABLES,
  TRAIN_CONFIGS_TABLE: TABLES.TRAIN_CONFIGS,
  TRAIN_GOAL_TRACKING_TABLE: TABLES.TRAIN_GOAL_TRACKING,
  TRAINING_CONFIG_DETAILS_TABLE: TABLES.TRAINING_CONFIG_DETAILS,
  VALIDATION_CONFIG_DETAILS_TABLE: TABLES.VALIDATION_CONFIG_DETAILS,
  SNAPSHOT_CONFIG_DETAILS_TABLE: TABLES.SNAPSHOT_CONFIG_DETAILS,
  ROLLING_POOL_DETAILS_TABLE: TABLES.ROLLING_POOL_DETAILS,
  ROLLING_RULE_DETAILS_TABLE: TABLES.ROLLING_RULE_DETAILS,
  ROUTER_CONFIG_DETAILS_TABLE: TABLES.ROUTER_CONFIG_DETAILS,
  POLICY_CONFIG_DETAILS_TABLE: TABLES.POLICY_CONFIG_DETAILS,
  GENERIC_CONFIG_DETAILS_TABLE: TABLES.GENERIC_CONFIG_DETAILS,
  TRAIN_RUN_REQUESTS_TABLE: TABLES.TRAIN_RUN_REQUESTS,
  TRAIN_ARTIFACTS_TABLE: TABLES.TRAIN_ARTIFACTS
};
